services:

  steam:
    build:
      dockerfile: Dockerfile
    image: ghcr.io/carlsonp/steam-analysis:latest
    restart: unless-stopped
    container_name: steam
    hostname: steam
    volumes:
      - ./logs:/logs:rw
    environment:
      TZ: "America/Chicago"
      MONGODB_IP: ${MONGODB_IP}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      STEAM_API_KEY: ${STEAM_API_KEY}
      ISTHEREANYDEAL_API_KEY: ${ISTHEREANYDEAL_API_KEY}
    depends_on:
      - mongo

  mongo:
    image: mongo:8.3.4
    restart: unless-stopped
    container_name: mongo
    hostname: mongo
    environment:
      TZ: "America/Chicago"
      MONGO_INITDB_DATABASE: "steam"
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    ports:
      - 27017:27017/tcp
    volumes:
      - mongodata:/data/db:rw

volumes:
  mongodata:
