FROM ubuntu:22.04

# https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md#run---mounttypecache
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt update && \
    apt install -y --no-install-recommends tzdata ca-certificates python3 python3-pip && \
    apt upgrade -y && \
    apt autoremove -y

RUN --mount=type=cache,target=/root/.cache/pip,sharing=locked pip3 install pymongo progressbar2 requests schedule beautifulsoup4

WORKDIR /

COPY *.py /

# for debugging
#CMD ["tail", "-f", "/dev/null"]
CMD ["python3", "-u", "run-schedule.py"]
