FROM ubuntu:24.04

# https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md#run---mounttypecache
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache

# install Mongo Tools
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt update && \
    apt install -y --no-install-recommends tzdata cron gnupg ca-certificates wget dos2unix libgssapi-krb5-2 libkrb5-3 libk5crypto3 libkrb5support0 libkeyutils1 && \
    wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2404-x86_64-100.10.0.deb && \
    dpkg --install mongodb-database-tools-ubuntu2404-x86_64-100.10.0.deb && \
    rm -rf mongodb-database-tools-ubuntu2404-x86_64-100.10.0.deb && \
    apt upgrade -y && \
    apt autoremove -y    

# create the executable script
COPY ./runbackup.sh /runbackup.sh
RUN chmod +x /runbackup.sh

# setup our mongo backup script to run via cron on a schedule
COPY mongobackup-crontab /etc/cron.d/mongobackup-crontab

RUN dos2unix /etc/cron.d/mongobackup-crontab

# https://stackoverflow.com/questions/37458287/how-to-run-a-cron-job-inside-a-docker-container

RUN chmod 0644 /etc/cron.d/mongobackup-crontab && \
    crontab /etc/cron.d/mongobackup-crontab

# for debugging
#CMD ["tail", "-f", "/dev/null"]
CMD ["cron", "-f"]
