FROM ubuntu:20.04

# for the local apt-cacher-ng proxy
RUN echo 'Acquire::HTTP::Proxy "http://192.168.1.226:3142";' >> /etc/apt/apt.conf.d/01proxy && \
    echo 'Acquire::HTTPS::Proxy "false";' >> /etc/apt/apt.conf.d/01proxy

RUN apt update && \
    apt install -y --no-install-recommends tzdata ca-certificates python3 python3-pip && \
    apt upgrade -y && \
    apt autoremove -y && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir pymongo progressbar2 requests schedule beautifulsoup4

WORKDIR /

COPY *.py /

# for debugging
#CMD ["tail", "-f", "/dev/null"]
CMD ["python3", "-u", "run-schedule.py"]