apiVersion: apps/v1
kind: Deployment
metadata:
  name: steam-analysis-mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0.34
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "chart.fullname" . }}-mongo-password-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              value: steam
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          ports:
            - name: mongodb
              containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: {{ include "chart.fullname" . }}-mongodb
