{{- if .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-mongodb
  labels:
    {{- with .Values.mongodb.persistence.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.mongodb.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.mongodb.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
{{- end }}
