apiVersion: v1
kind: Service
metadata:
  name: steam-analysis-mongodb
  namespace: steam-analysis
spec:
  type: LoadBalancer
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017